### ISSUE TITLE
Is project still active ?

### ISSUE THREAD

**Issue by PowerKiKi** [ogom/redmine_sidekiq#17]
@ogom, Is this project still active ? if not would you be willing to donate the project to a new organization dedicated to the plugin https://github.com/jbox-web/redmine_git_hosting and all its dependencies ?

**Comment by ogom** [comment]
thank you for contacting.
This is sometimes active.
And #16 merged.

**Comment by PowerKiKi** [comment]
Thanks for the merge. In the meantime we forked as https://github.com/redmine-git-hosting/redmine_sidekiq

Would you be interested in transferring ownership of this repository to the redmine-git-hosting organization ?

I would of course give you all the same access to the repository, so you loose nothing. But the project would gain a few maintainers. The users would benefit to have a single source of truth (no forks anymore). And the plugin redmine_git_hosting would not depend on a single person when fixes need to be made.

What do you think ?
